"""Precompute sprite trim boxes + clean green-screen fringes.

Outputs src/sprites_meta.js (global AR.SPRITE_META) so the game does not need
getImageData at runtime (works from file:// without canvas tainting issues).
Run from repo root:  python tools/build_sprite_meta.py
"""
import json, os, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GROUPS = {"hero": "assets/hero", "enemies": "assets/enemies"}

def despill(img):
    """Remove residual green-screen spill: greenish semi-transparent fringes."""
    px = img.load()
    w, h = img.size
    n = 0
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if a == 0:
                continue
            # strong green -> make transparent
            if g > 120 and g > r * 1.6 and g > b * 1.6:
                px[x, y] = (r, g, b, 0)
                n += 1
            # mild spill on edges -> clamp green channel
            elif g > 90 and g > r * 1.25 and g > b * 1.25 and a < 255:
                px[x, y] = (r, max(r, b), b, a)
                n += 1
    return n

def trim_box(img, alpha_min=8):
    """Bounding box of pixels with alpha > alpha_min."""
    a = img.getchannel("A")
    mask = a.point(lambda v: 255 if v > alpha_min else 0)
    box = mask.getbbox()
    return box if box else (0, 0, img.size[0], img.size[1])

meta = {}
total_spill = 0
for group, rel in GROUPS.items():
    folder = os.path.join(ROOT, rel)
    for fn in sorted(os.listdir(folder)):
        if not fn.endswith(".png"):
            continue
        path = os.path.join(folder, fn)
        img = Image.open(path).convert("RGBA")
        n = despill(img)
        if n > 0:
            img.save(path)
            total_spill += n
        x0, y0, x1, y1 = trim_box(img)
        key = f"{group}/{fn[:-4]}"
        meta[key] = {"w": img.size[0], "h": img.size[1],
                     "t": [x0, y0, x1 - x0, y1 - y0]}
        print(f"{key:40s} {img.size[0]}x{img.size[1]} trim={x0},{y0},{x1-x0},{y1-y0} spill={n}")

out = os.path.join(ROOT, "src", "sprites_meta.js")
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by tools/build_sprite_meta.py - do not edit.\n")
    f.write("window.AR = window.AR || {};\n")
    f.write("AR.SPRITE_META = " + json.dumps(meta, separators=(",", ":")) + ";\n")
print(f"\nWrote {out}  ({len(meta)} sprites, {total_spill} spill px fixed)")
