"""Precompute sprite trim boxes + clean green-screen fringes.

Outputs src/sprites_meta.js (global AR.SPRITE_META) so the game does not need
getImageData at runtime (works from file:// without canvas tainting issues).
Run from repo root:  python tools/build_sprite_meta.py
"""
import json, os, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GROUPS = {"hero": "assets/hero", "enemies": "assets/enemies", "spells": "assets/spells", "weapons": "assets/weapons"}

# Downscale caps (max dimension in px) by path fragment: keeps the repo light,
# the game never draws these bigger anyway.
MAX_DIM = {"spells/icons": 128, "hero/spells": 380}

# Certaines générations laissent un cadre résiduel sur les bords : on l'efface
# pour que la boîte de découpe colle au personnage.
BORDER_CLEAR = {"hero/spells": 6}


def clear_border(img, margin):
    w, h = img.size
    p = img.load()
    n = 0
    for y in range(h):
        for x in range(w):
            if x < margin or y < margin or x >= w - margin or y >= h - margin:
                r, g, b, a = p[x, y]
                if a:
                    p[x, y] = (r, g, b, 0)
                    n += 1
    return n


def is_green(px):
    r, g, b, a = px
    return a > 200 and g > 100 and g > r * 1.35 and g > b * 1.35


def chroma_key(img):
    """Remove an opaque green-screen background (detected via corner pixels)."""
    w, h = img.size
    p = img.load()
    corners = [p[0, 0], p[w - 1, 0], p[0, h - 1], p[w - 1, h - 1]]
    if sum(1 for c in corners if is_green(c)) < 3:
        return 0
    n = 0
    for y in range(h):
        for x in range(w):
            r, g, b, a = p[x, y]
            if a == 0:
                continue
            if g > 100 and g > r * 1.35 and g > b * 1.35:
                p[x, y] = (r, g, b, 0)
                n += 1
            elif g > max(r, b) * 1.15:
                # despill : ramener le vert au niveau des autres canaux
                p[x, y] = (r, int(max(r, b) * 1.1), b, a)
                n += 1
    return n

def despill(img):
    """Remove residual green-screen spill: greenish semi-transparent fringes."""
    px = img.load()
    w, h = img.size
    n = 0
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if a == 0:
                continue
            # strong green -> make transparent
            if g > 120 and g > r * 1.6 and g > b * 1.6:
                px[x, y] = (r, g, b, 0)
                n += 1
            # mild spill on edges -> clamp green channel
            elif g > 90 and g > r * 1.25 and g > b * 1.25 and a < 255:
                px[x, y] = (r, max(r, b), b, a)
                n += 1
    return n

def trim_box(img, alpha_min=8):
    """Bounding box of pixels with alpha > alpha_min."""
    a = img.getchannel("A")
    mask = a.point(lambda v: 255 if v > alpha_min else 0)
    box = mask.getbbox()
    return box if box else (0, 0, img.size[0], img.size[1])

meta = {}
total_spill = 0
for group, rel in GROUPS.items():
    folder = os.path.join(ROOT, rel)
    paths = []
    for current, _, files in os.walk(folder):
        paths.extend(os.path.join(current, fn) for fn in files if fn.endswith(".png"))
    for path in sorted(paths):
        fn = os.path.basename(path)
        img = Image.open(path).convert("RGBA")
        dirty = False
        n = chroma_key(img)
        n += despill(img)
        if n > 0:
            dirty = True
            total_spill += n
        # redimensionnement éventuel
        rel = os.path.relpath(path, ROOT).replace(os.sep, "/")
        for frag, cap in MAX_DIM.items():
            if frag in rel and max(img.size) > cap:
                ratio = cap / max(img.size)
                img = img.resize((max(1, round(img.size[0] * ratio)),
                                  max(1, round(img.size[1] * ratio))), Image.LANCZOS)
                dirty = True
        for frag, margin in BORDER_CLEAR.items():
            if frag in rel:
                if clear_border(img, margin) > 0:
                    dirty = True
        if dirty:
            img.save(path)
        x0, y0, x1, y1 = trim_box(img)
        sprite_name = os.path.relpath(path, folder).replace(os.sep, "/")[:-4]
        key = f"{group}/{sprite_name}"
        meta[key] = {"w": img.size[0], "h": img.size[1],
                     "t": [x0, y0, x1 - x0, y1 - y0]}
        print(f"{key:40s} {img.size[0]}x{img.size[1]} trim={x0},{y0},{x1-x0},{y1-y0} spill={n}")

out = os.path.join(ROOT, "src", "sprites_meta.js")
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by tools/build_sprite_meta.py - do not edit.\n")
    f.write("window.AR = window.AR || {};\n")
    f.write("AR.SPRITE_META = " + json.dumps(meta, separators=(",", ":")) + ";\n")
print(f"\nWrote {out}  ({len(meta)} sprites, {total_spill} spill px fixed)")
